import { z } from 'zod'

import {
  chatConversationStatusSchema,
  chatDeliveryStatusSchema,
  chatMessageSenderSchema,
  MAX_CHAT_MESSAGE,
} from '@/lib/chat-contracts'

const uuid = z.uuid()
const snowflake = z.string().regex(/^\d{1,30}$/u)
const dateTime = z.string().datetime({ offset: true })
const safeCode = z.string().regex(/^[a-z0-9_:-]{1,64}$/u)
const stableReference = z.string().regex(/^[A-Za-z0-9._:-]{1,160}$/u)
const stableNonce = z.string().regex(/^[A-Za-z0-9_-]{16,128}$/u)

export const chatDeliveryPartStateSchema = z.enum(['pending', 'claimed', 'uncertain', 'sent', 'failed'])
export type ChatDeliveryPartState = z.infer<typeof chatDeliveryPartStateSchema>

export const chatDeliveryFailureCodeSchema = safeCode
export type ChatDeliveryFailureCode = z.infer<typeof chatDeliveryFailureCodeSchema>

export const chatDeliveryOutcomeSchema = z.enum(['sent', 'uncertain', 'failed'])
export type ChatDeliveryOutcome = z.infer<typeof chatDeliveryOutcomeSchema>

/** Stable, body-free metadata generated by the bridge for each deterministic part. */
export const chatDeliveryPartDefinitionSchema = z.object({
  partIndex: z.number().int().min(0).max(19),
  stableReference,
  stableNonce,
}).strict()
export type ChatDeliveryPartDefinition = z.infer<typeof chatDeliveryPartDefinitionSchema>

export const chatDeliveryPartSchema = z.object({
  id: uuid,
  messageId: uuid,
  partIndex: z.number().int().min(0).max(19),
  partCount: z.number().int().min(1).max(20),
  stableReference,
  stableNonce,
  discordMessageId: snowflake.nullable(),
  state: chatDeliveryPartStateSchema,
  claimToken: uuid.nullable(),
  leaseExpiresAt: dateTime.nullable(),
  attemptCount: z.number().int().min(0).max(20),
  failureCode: safeCode.nullable(),
  nextRetryAt: dateTime.nullable(),
  createdAt: dateTime,
  updatedAt: dateTime,
}).strict()
export type ChatDeliveryPart = z.infer<typeof chatDeliveryPartSchema>

export const chatThreadLeaseSchema = z.object({
  conversationId: uuid,
  leaseToken: uuid,
  leaseExpiresAt: dateTime,
}).strict()
export type ChatThreadLease = z.infer<typeof chatThreadLeaseSchema>

export const chatStarterDeliverySchema = z.object({
  conversationId: uuid,
  starterMessageId: snowflake.nullable(),
  starterReference: stableReference.nullable(),
  starterNonce: stableNonce.nullable(),
  starterState: chatDeliveryPartStateSchema,
  claimToken: uuid.nullable(),
  claimExpiresAt: dateTime.nullable(),
  attemptCount: z.number().int().min(0).max(20),
  failureCode: safeCode.nullable(),
  nextRetryAt: dateTime.nullable(),
  threadId: snowflake.nullable(),
  threadLeaseToken: uuid.nullable(),
  threadLeaseExpiresAt: dateTime.nullable(),
}).strict()
export type ChatStarterDelivery = z.infer<typeof chatStarterDeliverySchema>

export const chatCleanupJobStateSchema = z.enum(['pending', 'claimed', 'uncertain', 'succeeded', 'failed'])
export type ChatCleanupJobState = z.infer<typeof chatCleanupJobStateSchema>

export const chatCleanupJobSchema = z.object({
  id: uuid,
  conversationId: uuid,
  guildId: snowflake,
  parentChannelId: snowflake,
  starterMessageId: snowflake.nullable(),
  threadId: snowflake.nullable(),
  state: chatCleanupJobStateSchema,
  claimToken: uuid.nullable(),
  leaseExpiresAt: dateTime.nullable(),
  attemptCount: z.number().int().min(0).max(20),
  failureCode: safeCode.nullable(),
  nextRetryAt: dateTime.nullable(),
  createdAt: dateTime,
  updatedAt: dateTime,
  completedAt: dateTime.nullable(),
}).strict()
export type ChatCleanupJob = z.infer<typeof chatCleanupJobSchema>

export const chatCleanupPreparationSchema = z.object({
  guildId: snowflake,
  parentChannelId: snowflake,
  cutoff: dateTime,
  limit: z.number().int().min(1).max(100).default(100),
}).strict()
export type ChatCleanupPreparation = z.infer<typeof chatCleanupPreparationSchema>

export const chatDeliveryWorkKindSchema = z.enum(['starter', 'starter_reconcile', 'message_prepare', 'part', 'part_reconcile'])
export type ChatDeliveryWorkKind = z.infer<typeof chatDeliveryWorkKindSchema>

export const chatDeliveryWorkCandidateSchema = z.object({
  conversationId: uuid,
  messageId: uuid.nullable(),
  partId: uuid.nullable(),
  workKind: chatDeliveryWorkKindSchema,
  state: z.string().regex(/^[a-z_]+$/u),
  attemptCount: z.number().int().min(0).max(20),
  nextRetryAt: dateTime.nullable(),
}).strict()
export type ChatDeliveryWorkCandidate = z.infer<typeof chatDeliveryWorkCandidateSchema>

/**
 * Server-only delivery reads deliberately omit display names and email.  The
 * bridge needs the Discord coordinates and state machine fields, but neither
 * optional contact information nor a visitor identity belongs in its query.
 */
export const chatDeliveryConversationSchema = z.object({
  id: uuid,
  status: chatConversationStatusSchema,
  discordDeliveryStatus: chatDeliveryStatusSchema,
  discordThreadId: snowflake.nullable(),
  discordThreadState: chatDeliveryPartStateSchema,
  discordThreadAttemptCount: z.number().int().min(0).max(20),
  discordThreadFailureCode: safeCode.nullable(),
  discordThreadNextRetryAt: dateTime.nullable(),
  discordStarterMessageId: snowflake.nullable(),
  discordStarterReference: stableReference.nullable(),
  discordStarterNonce: stableNonce.nullable(),
  discordStarterState: chatDeliveryPartStateSchema,
  discordStarterClaimToken: uuid.nullable(),
  discordStarterClaimExpiresAt: dateTime.nullable(),
  discordStarterAttemptCount: z.number().int().min(0).max(20),
  discordStarterFailureCode: safeCode.nullable(),
  discordStarterNextRetryAt: dateTime.nullable(),
}).strict()
export type ChatDeliveryConversation = z.infer<typeof chatDeliveryConversationSchema>

/** Body-bearing reads are kept in a distinct internal contract. */
export const chatDeliveryMessageSchema = z.object({
  id: uuid,
  conversationId: uuid,
  sender: chatMessageSenderSchema,
  body: z.string().trim().min(1).max(MAX_CHAT_MESSAGE),
  deliveryStatus: chatDeliveryStatusSchema,
  deliveryPartCount: z.number().int().min(1).max(20).nullable(),
  createdAt: dateTime,
}).strict()
export type ChatDeliveryMessage = z.infer<typeof chatDeliveryMessageSchema>
